"""TTS provider constants."""

DEFAULT_MAX_TEXT_LENGTH = 5000
DEFAULT_WORDS_PER_MINUTE = 150
SUPPORTED_AUDIO_FORMATS = frozenset({"wav", "mp3", "opus"})
VOICE_CACHE_TTL_SECONDS = 300
HEALTH_CACHE_TTL_SECONDS = 60
