"""Script generation configuration constants."""

PROMPT_VERSION = "v2.0.0"
MIN_SEGMENTS = 20
MAX_SEGMENTS = 80
MAX_ESTIMATED_DURATION_SECONDS = 30 * 60
WORDS_PER_MINUTE = 150
DEFAULT_TONE = "conversational"
DEFAULT_LANGUAGE = "en"

ARTICLE_START = "<<<ARTICLE_START>>>"
ARTICLE_END = "<<<ARTICLE_END>>>"
