# Generated by Django 5.2.15 on 2026-06-29 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("episodes", "0001_initial"),
        ("scripts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "provider",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("file_path", models.CharField(max_length=500)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in seconds.", null=True
                    ),
                ),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        blank=True, help_text="File size in bytes.", null=True
                    ),
                ),
                (
                    "checksum",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio_assets",
                        to="episodes.episode",
                    ),
                ),
                (
                    "script_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audio_assets",
                        to="scripts.scriptsegment",
                    ),
                ),
            ],
            options={
                "ordering": ["episode", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["episode", "status"],
                        name="audio_audio_episode_2fe7d8_idx",
                    ),
                    models.Index(
                        fields=["episode", "script_segment"],
                        name="audio_audio_episode_a778cc_idx",
                    ),
                ],
            },
        ),
    ]
