# Generated by Django 5.2.15 on 2026-06-29 22:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("rss", "RSS"),
                            ("html", "HTML"),
                            ("api", "API"),
                            ("manual", "Manual"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("homepage", models.URLField(blank=True, max_length=500)),
                ("rss_url", models.URLField(blank=True, max_length=500)),
                (
                    "language",
                    models.CharField(db_index=True, default="en", max_length=10),
                ),
                ("enabled", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["enabled", "provider_type"],
                        name="providers_n_enabled_1af095_idx",
                    )
                ],
            },
        ),
    ]
