# Generated by Django 5.2.15 on 2026-06-29 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublishJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("rss", "RSS"),
                            ("spotify", "Spotify"),
                            ("twitch", "Twitch"),
                            ("webapp", "Web App"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("published_url", models.URLField(blank=True, max_length=1000)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_jobs",
                        to="episodes.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["episode", "platform"],
                        name="publish_pub_episode_f60164_idx",
                    ),
                    models.Index(
                        fields=["status", "platform"],
                        name="publish_pub_status_99464c_idx",
                    ),
                ],
            },
        ),
    ]
