# Generated by Django 5.2.15 on 2026-06-29 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(db_index=True, default="en", max_length=10),
                ),
                (
                    "publish_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("collecting", "Collecting"),
                            ("generating_script", "Generating Script"),
                            ("generating_audio", "Generating Audio"),
                            ("publishing", "Publishing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("cover_image", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-publish_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EpisodeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_articles",
                        to="articles.article",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_articles",
                        to="episodes.episode",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="episode",
            name="articles",
            field=models.ManyToManyField(
                blank=True,
                related_name="episodes",
                through="episodes.EpisodeArticle",
                to="articles.article",
            ),
        ),
        migrations.AddConstraint(
            model_name="episodearticle",
            constraint=models.UniqueConstraint(
                fields=("episode", "article"), name="unique_episode_article"
            ),
        ),
        migrations.AddIndex(
            model_name="episode",
            index=models.Index(
                fields=["status", "publish_date"], name="episodes_ep_status_60ad40_idx"
            ),
        ),
    ]
