# Generated by Django 5.2.15 on 2026-06-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="classified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="importance_score",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="keywords_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["importance_score", "published_at"],
                name="articles_ar_importa_a9586d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["category", "importance_score"],
                name="articles_ar_categor_1dff48_idx",
            ),
        ),
    ]
