# Generated by Django 5.2.15 on 2026-06-29 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("episodes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("llm_provider", models.CharField(blank=True, max_length=100)),
                ("prompt_version", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("approved", "Approved"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scripts",
                        to="episodes.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["episode", "-version"],
            },
        ),
        migrations.CreateModel(
            name="ScriptSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "speaker",
                    models.CharField(
                        choices=[("expert", "Expert"), ("beginner", "Beginner")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("voice", models.CharField(blank=True, max_length=100)),
                ("emotion", models.CharField(blank=True, max_length=50)),
                ("text", models.TextField()),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "script",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="scripts.script",
                    ),
                ),
            ],
            options={
                "ordering": ["script", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="script",
            index=models.Index(
                fields=["episode", "status"], name="scripts_scr_episode_602283_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="script",
            constraint=models.UniqueConstraint(
                fields=("episode", "version"), name="unique_episode_script_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="scriptsegment",
            constraint=models.UniqueConstraint(
                fields=("script", "sequence"), name="unique_script_segment_sequence"
            ),
        ),
    ]
