"""Episode planning constants."""

MAX_EPISODE_ARTICLES = 5
MAX_EPISODE_MINUTES = 25
MAX_EPISODE_SECONDS = MAX_EPISODE_MINUTES * 60
ESTIMATED_SECONDS_PER_ARTICLE = MAX_EPISODE_SECONDS // MAX_EPISODE_ARTICLES
MIN_KEYWORDS = 5
MAX_KEYWORDS = 15
